apiVersion: databricks.microsoft.com/v1alpha1
kind: Run
metadata:
  name: drun-basic1
spec:
  # create a run directly without a job
  new_cluster:
    spark_version: 5.5.x-scala2.11
    node_type_id: Standard_D3_v2
    num_workers: 3
  notebook_task:
    base_parameters:
      "name":  "r752960"
    notebook_path: "/Shared/irjx/basic1"
